name: Update Android

on:
    workflow_dispatch:

    push:
        branches:
            - "build/release"
        tags:
          - 'v*'

jobs:
    update_android:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3


            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'oracle'

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '16.13'
#                node-version: '20.1'

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: get latest tag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              id: get-latest-tag
              with:
                fallback: latest

            - name: Cache
              uses: actions/cache@v1
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/packagge-lock.json')}}
                restore-keys: |
                    ${{ runner.os }}-node-
            
            - run: npm i -g @quasar/cli
            - run: npm install

            - name: Build resource
              run: cd packages/app/;PLATFORM=MOBILE quasar build -m capacitor -T android --skip-pkg

            - name: Build unsigned apk
              run: cd packages/app/src-capacitor/android;./gradlew assembleRelease

            - uses: r0adkll/sign-android-release@v1
              name: Sign app
              id: sign_app
              with:
                releaseDirectory: packages/app/src-capacitor/android/app/build/outputs/apk/release
                signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
                alias: ${{ secrets.ANDROID_ALIAS }}
                keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
                keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
              env:
                BUILD_TOOLS_VERSION: "33.0.1"

            - name: Show path
              run: ls -a packages/app/src-capacitor/android/app/build/outputs/apk/release

            - name: Get signed release file path and extract filename
              id: get_signed_release_file_and_filename
              run: |
                SIGNED_RELEASE_FILE=${{ steps.sign_app.outputs.signedReleaseFile }}
                echo "SIGNED_RELEASE_FILE=${SIGNED_RELEASE_FILE}" >> $GITHUB_ENV
                FILENAME=$(basename "${SIGNED_RELEASE_FILE}")
                echo "FILENAME=${FILENAME}" >> $GITHUB_ENV

            - name: Rename signed APK
              run: |
                ORIGINAL_FILE=${{ env.SIGNED_RELEASE_FILE }}
                RENAMED_FILE=$(echo "$ORIGINAL_FILE" | sed 's/-release-unsigned-signed//')
                mv "$ORIGINAL_FILE" "$RENAMED_FILE"
                echo "RENAMED_FILE=$RENAMED_FILE" >> $GITHUB_ENV
                RENAMED_FILENAME=$(basename "${RENAMED_FILE}")
                echo "RENAMED_FILENAME=${RENAMED_FILENAME}" >> $GITHUB_ENV

            - name: Release Android app
              uses: djnicholson/release-action@v2.11
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                release-name: TermiPass-apk Release
                tag-name: ${{ steps.get-latest-tag.outputs.tag }}
                asset-name: ${{ env.RENAMED_FILENAME }}
                file: ${{ env.RENAMED_FILE }}